import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import { useRouter } from 'next/router';

export default function Home() {
	const router = useRouter();
	const handleOnSubmit = (event) => {
		event.preventDefault();
		console.log(event.currentTarget);
		let id = Array.from(event.currentTarget.elements).find(
			({ name }) => name === 'id'
		).value;
		// Don't capture anything upto the 3rd "/"
		// then capture everything until you get a "?" or a "#" and then don't capture the rest.
		//Replace everything with the captured value

		const idUrl = id.replace(
			/(https?:\/\/)?(www\.)?youtu((\.be)|(be\..{2,5}))\/((user)|(channel)|(c)|())\//g,
			''
		);
		router.push(`/milestone/${id}`);
		console.log('idUrl', idUrl);
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href='https://nextjs.org'>Next.js!</a>
				</h1>

				<p className={styles.description}>
					Get started by editing{' '}
					<code className={styles.code}>pages/index.js</code>
				</p>

				<div className={styles.grid}>
					<form
						className='form'
						onSubmit={handleOnSubmit}
						method='post'>
						<div className='formWrapper'>
							<label htmlFor='id'></label>
							<input type='text' name='id' id='id' />
						</div>
						<button>submit</button>
					</form>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'>
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src='/vercel.svg'
							alt='Vercel Logo'
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
}
